version: "3.3"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: workout-scheduler
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./data/fixtures:/fixtures
      - ./data/mongo_import.sh:/docker-entrypoint-initdb.d/mongo_import.sh
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


volumes:
  mongodb_data:
    driver: local
